name: Android Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11    
      uses: actions/setup-java@v4    
      with:    
        java-version: '11'    
        distribution: 'temurin'    
        cache: gradle

    - name: Android Emulator Tests
      uses: ReactiveCircus/android-emulator-runner@v2.30.1
      with:
        api-level: 29
        script: ./gradlew connectedCheck
            
