name: Android CI 

on:    
  push:    
    branches: [ master ]    
  pull_request:    
    branches: [ master ]    

jobs:    
  build:    
    runs-on: ubuntu-latest    
    steps:    
      # Checkout code    
      - uses: actions/checkout@v4    

      # Setup Java JDK 17    
      - name: Set up JDK 17    
        uses: actions/setup-java@v4    
        with:    
          java-version: '17'    
          distribution: 'temurin'    
          cache: gradle
          
      # Build and execute JUnit tests    
      - name: Build and Run JUnit Tests    
        run: ./gradlew test  
