name: Android CI

on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurun'
         cache: gradle

     - name: Grant execute permission on Gradle wrapper
       run: chmod +x gradlew

     - name: Build and execute JUnit tests
       run: ./gradlew test

     - name:  Execute Espresso (Instrumented) tests 
       uses: actions/checkout@v4
       with:
         fetch-depth: 0 
       run: ./gradlew connectedAndroidTest 
